#ifndef _WINDOWTYPES_H_
#define _WINDOWTYPES_H_

#define WT_CARD "_WEBOS_WINDOW_TYPE_CARD"
#define WT_POPUP "_WEBOS_WINDOW_TYPE_POPUP"
#define WT_MINIMAL "_WEBOS_WINDOW_TYPE_RESTRICTED"
#define WT_OVERLAY "_WEBOS_WINDOW_TYPE_OVERLAY"
#define WT_NONE "_WEBOS_WINDOW_TYPE_NONE"
#define WT_FLOATING "_WEBOS_WINDOW_TYPE_FLOATING"
#define WT_UNKNOWN "_WEBOS_WINDOW_TYPE_UNKNOWN"
#define WT_SYSTEM_UI "_WEBOS_WINDOW_TYPE_SYSTEM_UI"

#endif // _WINDOWTYPES_H_
